packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@prisma/engines': true
  '@scarf/scarf': true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true

onlyBuiltDependencies:
  - "@prisma/engines"
  - "@scarf/scarf"
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
