export enum AmenityEnum {
  AirConditioning = "AirConditioning",
  Washer = "Washer",
  Dryer = "Dryer",
  Refrigerator = "Refrigerator",
  Microwave = "Microwave",
  Dishwasher = "Dishwasher",
  Oven = "Oven",
  Kitchen = "Kitchen",
  WiFi = "WiFi",
  Television = "Television",
  Parking = "Parking",
  Elevator = "Elevator",
  SwimmingPool = "SwimmingPool",
  Gym = "Gym",
  Balcony = "Balcony",
  Garden = "Garden",
  CCTV = "CCTV",
  Furnished = "Furnished",
}
