export enum HighlightEnum {
  NewlyRenovated = "NewlyRenovated",
  NewlyBuilt = "NewlyBuilt",
  PrimeLocation = "PrimeLocation",
  CityView = "CityView",
  SeaView = "SeaView",
  MountainView = "MountainView",
  RiverView = "RiverView",
  QuietNeighborhood = "QuietNeighborhood",
  NearSchool = "NearSchool",
  NearHospital = "NearHospital",
  NearSupermarket = "NearSupermarket",
  NearPublicTransport = "NearPublicTransport",
  HighSecurityArea = "HighSecurityArea",
  SpaciousLayout = "SpaciousLayout",
  NaturalLight = "NaturalLight",
  PetFriendlyCommunity = "PetFriendlyCommunity",
}
